Repository BuildForSDG/FASTA-FRONTEND, pull requests merged in 2020-06, with the labels that each got.

#3 login done
  components/Account/account.js
  package-lock.json
  pages/login.js
Labels: bug

#5 add popup
  README.md
  app.properties
  components/OnBoardingLayout/Layout.js
  components/Popup.js
Labels: enhancement

#7 Update README.md
  README.md
Labels: documentation

#8 logout button
  components/Homepage/NavBar.js
  package.json
Labels: enhancement
